### ISSUE TITLE
Filter blocks according to forger

### ISSUE THREAD

**Issue by evaarnas** [fimkrypto/mofowallet#11]
I'd like to find which blocks a certain account has forged. That was possible in the old block explorer, but can't find that information from mofowallet.

**Comment by evaarnas** [comment]
Please help @fimkrypto, a beer for a solution! (powered by @ChangeTip)

**Comment by changetip** [comment]
Hi @fimkrypto, @evaarnas sent you a Bitcoin tip worth a beer (14,557 bits/$3.50), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/828329)**.


**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**

**Comment by fimkrypto** [comment]
Hi evaarnas,

So sorry for this (extremely) late reaction, seems like my email notification for issues is wrongly configured, just seeing this now.

You can still see that info if you go here for instance https://www.mofowallet.com/launch.html#/accounts/FIM-DK4B-Z8ED-9RS3-7ZVRR/blocks/latest

To get there go to any account page, click More then click Blocks forged.

Dirk

**Comment by evaarnas** [comment]
Thanks and sorry, I already found that URL.

@fimkrypto, the beer went bad in the meantime (it was refunded), here's another one @ChangeTip

**Comment by changetip** [comment]
Hi @fimkrypto, @evaarnas sent you a Bitcoin tip worth 1 beer (14,726 bits/$3.50), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/857935)**.


**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**
